name: Code Quality

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  tests:
    name: Javascript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
