on:
  push:
    tags:
      - 'v*'

name: Publish release

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload release asset snowboard.js
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packages/base/dist/snowboard.js
          asset_name: snowboard.js
          asset_content_type: application/javascript

      - name: Upload release asset snowboard.min.js
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packages/base/dist/snowboard.min.js
          asset_name: snowboard.min.js
          asset_content_type: application/javascript

      - name: Upload release asset snowboard-controls.js
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packages/controls/dist/snowboard-controls.js
          asset_name: snowboard-controls.js
          asset_content_type: application/javascript

      - name: Upload release asset snowboard-controls.min.js
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packages/controls/dist/snowboard-controls.min.js
          asset_name: snowboard-controls.min.js
          asset_content_type: application/javascript

      - name: Upload release asset snowboard-reactivity.js
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packages/reactivity/dist/snowboard-reactivity.js
          asset_name: snowboard-reactivity.js
          asset_content_type: application/javascript

      - name: Upload release asset snowboard-reactivity.min.js
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packages/reactivity/dist/snowboard-reactivity.min.js
          asset_name: snowboard-reactivity.min.js
          asset_content_type: application/javascript
